modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wildscapes"
version = "${version}"
displayName = "Wild Scapes"
authors = "Me!"
description = '''

'''
#logoFile = ""

[[dependencies.wildscapes]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wildscapes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wildscapes]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"